# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  identifier = "pubs"
  weight = 40

[[main]]
  name = "Full list"
  parent = "pubs"
  url = "publication/"
  weight = 20

[[main]]
  name = "Featured"
  parent = "pubs"
  url = "#featured"
  weight = 10

[[main]]
  name = "Teaching"
  url = "teaching/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

[[mlis_rl]]
  name = "Overview"
  weight = 10
  url = "/teaching/mlis_rl/"

[[mlis_rl]]
  name = "Deterministic Reinforcement Learning"
  weight = 20
  identifier = "det_rl"

[[mlis_rl]]
  name = "Policy Gradients and deep RL"
  weight = 30
  identifier = "pg_drl"

[[mlis_rl]]
  name = "Example code"
  weight = 40
  identifier = "ex_code"

[[mlis_rl]]
  name = "Answers"
  weight = 50
  identifier = "ans"
